name: 'Build and Test'

on: [push, pull_request]

jobs:

  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-restore --no-build -v=normal --collect:"XPlat Code Coverage"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload NoStringEvaluating nuget packages artifacts
      uses: actions/upload-artifact@v4
      with:
        name: service-nuget-packages
        path: NoStringEvaluating/bin/Release/*.nupkg
        retention-days: 1

    - name: Upload NoStringEvaluating.DI nuget packages artifacts
      uses: actions/upload-artifact@v4
      with:
        name: service-di-nuget-packages
        path: NoStringEvaluating.Extensions.Microsoft.DependencyInjection/bin/Release/*.nupkg
        retention-days: 1

